<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('MUDPuddle')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/foundation.css'))
                        ->prependStylesheet($this->basePath('css/normalize.css'))?>
<!-- TODO: Sort out favicon -->
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
        <nav class="top-bar" data-topbar role="navigation">
            <ul class="title-area">
                <li>
                    <h3><a href="/">MUDPuddle</a></h3>
                </li>
            </ul>

            <section class="top-bar-section">
                <ul class="right">
                    <li class="has-dropdown">
                        <a href="#">Navigation Menu</a>
                        <ul class="dropdown">
                            <li><a href="#">First link in dropdown</a></li>
                        </ul>
                    </li>
                </ul>
            </section>

        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p> &copy <?php echo date('Y') ?> MUDPuddle <?php echo $this->translate('Free for all.') ?></p>
            </footer>
        </div> <!-- /container -->
        <script src="<?=$this->basePath('js/vendor/jquery.js'); ?>"></script>
        <script src="<?=$this->basePath('js/foundation/foundation.js'); ?>"></script>
        <script src="<?=$this->basePath('js/foundation/foundation.topbar.js'); ?>"></script>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>
